# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eea222d814507ef484e17ee36e8d5c374629a06930ac4690632fa9533c9a00ca83fd01c170622d7ffc47f15bf056fd5749b582d48438f344b624ee3baa9c47b1

test:
  secret_key_base: 67b0dec3eb09bb53cb0dc26a33598f500a058284bd2abc88363bba1b6a06ddfe232f15c5963631ecb63424133e1f4762a6c4015afbfe1848201367da944a4cc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
